name: Build & Test
on:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '16'
    - name: aaa
      run: |
          echo "1111111"
          printenv
