on:
  pull_request:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - run: |
        echo "running pull request target"
  build2:
    runs-on: ubuntu-22.04
    steps:
    - run: |
            echo "777"
            echo The Title of your PR is unknown
