name: CI
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - run: |
        echo "running pull request target"
  build2:
    runs-on: ubuntu-22.04
    steps:
    - run: |
            echo "124"
            echo "${{ secrets.test1 }}"
            echo The Title of your PR is ${{ github.event.pull_request.title }}
