on:
  issue_comment:
    types: [ created ]

permissions:
  pull-requests: write
  contents: read

jobs:
  myjob:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/doit')
    steps:
      - uses: gotson/pull-request-comment-branch@head-repo-owner-dist
        id: comment-branch
      - uses: actions/checkout@v4
        with:
          repository: ${{ steps.comment-branch.outputs.head_owner }}/${{ steps.comment-branch.outputs.head_repo }}
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - run: |
          git config --global --add safe.directory "*"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          echo "aaa" > opa.txt
          git add .
          git commit -m "Update"
          git push origin HEAD:${{ steps.comment-branch.outputs.head_ref }}
